baseURL = 'https://ljnolan.github.io/'
locale = 'en-us'
title = "Liam Nolan's Personal Website"
theme = "paige"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[paige.pages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_next = true
disable_prev = true
disable_reading_time = true
disable_series = true
disable_toc = true
disable_word_count = true

[paige.subpages]
disable_authors = true
disable_date = true
disable_keywords = true
disable_reading_time = true
disable_series = true
disable_summary = true
disable_word_count = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
name = "CV"
url = "/cv/"
weight = 3

[params.paige.site]
disable_breadcrumbs = true
